# Subscription.destroy_all

User.destroy_all
u1 = User.create!(email: "a@a.com", password: "12121212", username: "a")
u2 = User.create!(email: "b@b.com", password: "12121212", username: "b")
u3 = User.create!(email: "c@c.com", password: "12121212", username: "c")

Artist.destroy_all
a1 = Artist.create!(name: "Mulatto Patriot", record_label: "Independent")
a2 = Artist.create!(name: "Kendrick Lamar", record_label: "TDE")
a3 = Artist.create!(name: "Action Bronson", record_label: "Major")
a4 = Artist.create!(name: "Kanye West", record_label: "Major")
a5 = Artist.create!(name: "Chance the Rapper", record_label: "Independent")
a6 = Artist.create!(name: "Lili K", record_label: "Independent")
a7 = Artist.create!(name: "Third Eye Blind", record_label: "Major")
a8 = Artist.create!(name: "The Omy's", record_label: "Independent")
a9 = Artist.create!(name: "Snoop Dogg", record_label: "Major")
a10 = Artist.create!(name: "Vic Mensa", record_label: "Roc Nation")

Album.destroy_all
p1 = Album.create!(artist: a1, name: "Ray Elementary", release_date: "{2014/1/23}", download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '<iframe src="http://www.audiomack.com/embed4-album/mulatto-patriot/ray-elementary" scrolling="no" width="100%" height="350" scrollbars="no" frameborder="0"></iframe>', itunes: "", google: "", amazon: "", spotify: "", youtube: '' )
p2 = Album.create!(artist: a2, name: "To Pimp A Butterfly", release_date: "{2015/3/16}", download_link: "", embedded_code: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP", youtube: '' )
p3 = Album.create!(artist: a3, name: "Mr Wonderful", release_date: "{2015/3/23}", download_link: "", embedded_code: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd", youtube: '' )


Song.destroy_all
s = Song.create!(title: "Stop On By", artist: a1, features: "Neak, Primeridian", producer: "Mulatto Patriot", album_id: "", track: "", album_title: "", release_date: "{2014/12/20}", youtube: '', itunes: "", amazon: "", google: "",  spotify: "", download_link: "https://soundcloud.com/mulatto-patriot/stop-on-by-primeridian-neak", embedded_code: '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/141553411&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>')
s = Song.create!(title: "U Mad", artist: a10, features: "Kanye West", producer: "Kanye West", album_id: "" , track: "", album_title: "", release_date: "{2015/4/20}", youtube: '', itunes: "https://itunes.apple.com/us/album/u-mad-feat.-kanye-west-single/id987725958", amazon: "http://www.amazon.com/Mad-feat-Kanye-West-Explicit/dp/B00WFNG43M", google: "https://play.google.com/store/music/artist/Vic_Mensa?id=Aqtlm7ha7rv7lmv7gdgkkjqdlqm&hl=en", spotify: "https://play.spotify.com/album/0ssmI1Nu1oYmi13w6GaiDJ",  download_link: "", embedded_code: '' )
s = Song.create!(title: "SoundCatcher", artist: a1, features: "Pugs Atomz, Neak", producer: "Mulatto Patriot", album_id: "", track: "" , album_title: "The New Deal", release_date: "{2012/2/13}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/li_IsOlb8VY?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "", amazon: "", google: "",  spotify: "", download_link: "http://mulattopatriot.bandcamp.com/track/soundcatcher-feat-pugs-atomz-neak", embedded_code: '<iframe style="border: 0; width: 100%; height: 42px;" src="http://bandcamp.com/EmbeddedPlayer/album=1973410984/size=small/bgcol=ffffff/linkcol=0687f5/track=4116145876/transparent=true/" seamless><a href="http://mulattopatriot.bandcamp.com/album/the-promise-the-new-deal">The Promise &quot;The New Deal&quot; by The Promise (Squair Blaq &amp; Mulatto Patriot)</a></iframe>')
s = Song.create!(title: "Coco Butter Kisses", artist: a5, features: "Vic Mensa, Twista", producer: "Peter Cottontale", album_id: "", track: "", album_title: "Acid Rap", release_date: "{2013/4/30}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/TErySTMbFlk?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "", amazon: "", google: "", spotify: "",  download_link: "https://soundcloud.com/chancetherapper/cocoa-butter-kisses-ft-vic", embedded_code: %^<<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/90243752&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>^ )
s = Song.create!(title: "Only One", artist: a4, features: "Paul McCartney", producer: "", album_id: "", track: "", album_title: "", release_date: "{2014/12/31}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/WibQR0tQ0P8?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/only-one-feat.-paul-mccartney/id955053780", amazon: "http://www.amazon.com/Only-One-feat-Paul-McCartney/dp/B00RW7UZO0", google: "", spotify: "",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Lady Friend", artist: a5, features: "The Social Experiment", producer: "The Social Experiment", album_id: "", track: "", album_title: "", release_date: "{2015/2/14}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/h8nIHZ-0kS4?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "", amazon: "", google: "", spotify: "",  download_link: "https://soundcloud.com/chancetherapper/chance-the-rapper-the-social-experiment-lady-friend", embedded_code: '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/191163281&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>' )
s = Song.create!(title: "No Better Blues", artist: a5, features: "The Social Experiment", producer: "The Social Experiment", album_id: "", track: "", album_title: "", release_date: "{2014/10/16}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "https://soundcloud.com/chancetherapper/chance-the-rapper-the-social-experiment-know-betta-blues", embedded_code: '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/172307425&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>' )
s = Song.create!(title: "All Day", artist: a4, features: "Allan Kingdom & Theophilus London", producer: "", album_id: "", track: "", album_title: "So Help Me God", release_date: "{2015/3/2}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/_ABk7TmjnVk?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/all-day-feat.-theophilus-london/id972815455", amazon: "http://www.amazon.com/All-Day-Explicit-Kanye-West/dp/B00U6P6CW4", google: "https://play.google.com/store/music/album/Kanye_West_All_Day?id=Bok2mgdce7hjbvpmlzfoanjnb7i&hl=en", spotify: "https://play.spotify.com/user/cmount/playlist/0uFxjmYfjEXObrgiKmoavw",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Awsome", artist: a4, features: "", producer: "", album_id: "", track: "", album_title: "So Help Me God", release_date: "{2015/3/2}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/xz-QrOo1UBE?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "", amazon: "", google: "", spotify: "",  download_link: "", embedded_code: '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/195458522&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>' )

s = Song.create!(title: "Wesley\'s Theory", artist: a2, features: "George Clinton, Thundercat", producer: "", album: p2, track: "1", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "For Free\? (Interlude)", artist: a2, features: "", producer: "", album: p2, track: "2", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "King Kunta", artist: a2, features: "", producer: "", album: p2, track: "3", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/hRK7PVJFbS8?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Institutionalized", artist: a2, features: "Bilal, Anna Wise & Snoop Dogg", producer: "", album: p2, track: "4", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "These Walls", artist: a2, features: "Bilal, Anna Wise & Thundercat", producer: "", album: p2, track: "5", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "U", artist: a2, features: "", producer: "", album: p2, track: "6", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Alright", artist: a2, features: "", producer: "", album: p2, track: "7", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "For Sale\? (Interlude)", artist: a2, features: "", producer: "", album: p2, track: "8", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Momma", artist: a2, features: "", producer: "", album: p2, track: "9", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Hood Politics", artist: a2, features: "", producer: "", album: p2, track: "10", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "How Much A Dollar Cost", artist: a2, features: "James Fauntleroy & Ronald Isley", producer: "", album: p2, track: "11", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Complexion (A Zulu Love)", artist: a2, features: "Rapsody", producer: "", album: p2, track: "12", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "The Blacker The Berry", artist: a2, features: "", producer: "", album: p2, track: "13", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "You Ain\'t Gotta Lie (Momma Said)", artist: a2, features: "", producer: "", album: p2, track: "14", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "I", artist: a2, features: "", producer: "", album: p2, track: "15", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/8aShfolR6w8?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Mortal Man", artist: a2, features: "", producer: "", album: p2, track: "16", album_title: "To Pimp A Butterfly", release_date: "{2015/3/16}", youtube: '', itunes: "https://itunes.apple.com/us/album/to-pimp-a-butterfly/id974187289", amazon: "http://www.amazon.com/To-Pimp-Butterfly-Kendrick-Lamar/dp/B00UDDM7K0", google: "https://play.google.com/store/music/album/Kendrick_Lamar_To_Pimp_A_Butterfly?id=Bxno4dwxtvymibbibjafrmsk5fi&hl=en", spotify: "https://play.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP",  download_link: "", embedded_code: '' )

s = Song.create!(title: "Brand New Car", artist: a3, features: "", producer: "Mark Ronson", album: p3, track: "1", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "The Rising", artist: a3, features: "", producer: "Statik Selektah", album: p3, track: "2", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Terry", artist: a3, features: "", producer: "The Alchemist", album: p3, track: "3", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: ' ', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Actin Crazy", artist: a3, features: "Chance the Rapper", producer: "40", album: p3, track: "4", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/debIyWS6Byc?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Falconry", artist: a3, features: "", producer: "he Alchemist", album: p3, track: "5", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "THUG LOVE STORY 2017 THE MUSICAL (interlude)", artist: a3, features: "", producer: "", album: p3, track: "6", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "City Boy Blues", artist: a3, features: "", producer: "88-Keys", album: p3, track: "7", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "A Light In The Addict", artist: a3, features: "", producer: "Party Supplies", album: p3, track: "8", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Baby Blue", artist: a3, features: "", producer: "Mark Ronson", album: p3, track: "9", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/bVP_w1rQweE?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Only In America", artist: a3, features: "", producer: "Oh No", album: p3, track: "10", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Galactic Love", artist: a3, features: "", producer: "The Alchemist", album: p3, track: "11", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "The Passage (Live From Prague)", artist: a3, features: "", producer: "Party Supplies", album: p3, track: "12", album_title: "Mr Wonderful", release_date: "{2015/3/23}", youtube: '', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )
s = Song.create!(title: "Easy Rider", artist: a3, features: "", producer: "Party Supplies", album: p3, track: "", album_title: "Mr Wonderful13", release_date: "{2015/3/23}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/58RSC7HO9aU?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "https://itunes.apple.com/us/album/mr.-wonderful/id965629356", amazon: "http://www.amazon.com/Mr-Wonderful-Explicit-Action-Bronson/dp/B00TA6L6O4", google: "https://play.google.com/store/music/album/Action_Bronson_Mr_Wonderful?id=Bxihcl7ae23bfw5sm5mypnikrme&hl=en", spotify: "https://play.spotify.com/album/6jZzqlKfTvx4nON67dyCXd",  download_link: "", embedded_code: '' )

s = Song.create!(title: "Drum Line", artist: a1, features: "Sincerely Yours", producer: "Mulatto Patriot", album: p1, track: "1", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Funky Junkie", artist: a1, features: "Psalm One", producer: "Mulatto Patriot", album: p1, track: "2", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementaryhttps://soundcloud.com/mulatto-patriot/mulatto-patriot-primeridians", embedded_code: '<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/129683095&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>' )
s = Song.create!(title: "Mysterious Vibes", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "3", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Once Again", artist: a1, features: "Pugs Atomz, ProbCause", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/kkyHXnaQf_Y?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Show to Show", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "The Streets are Chanting 4U", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Crazy Love", artist: a1, features: "Greg Blackman", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "When the Birds Fly", artist: a1, features: "Imani(Pharcyde), Maggie Vagle", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Writters Block", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Funkorama", artist: a1, features: "Awdazcate", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Hot Day", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '<iframe width="853" height="480" src="https://www.youtube.com/embed/Nk7SfADrIxI?rel=0" frameborder="0" allowfullscreen></iframe>', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Lifestyles", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )
s = Song.create!(title: "Something Special", artist: a1, features: "", producer: "Mulatto Patriot", album: p1, track: "", album_title: "Ray Elementary", release_date: "{2014/1/23}", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "http://www.audiomack.com/album/mulatto-patriot/ray-elementary", embedded_code: '' )


#   # {title: "", artist: , features: "", producer: "", album , track: "", album_title: "", release_date: "", youtube: '', itunes: "", amazon: "", google: "", spotify: "",  download_link: "", embedded_code: ''  },

# ])
